version: '3.8'

services:
  api-buying:
    build: .
    ports:
      - '3000:3000'
    container_name: api-buying
    depends_on:
      - mysql
    env_file:
      - .env
    networks:
      - mynetwork

  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: api-buying-database
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork

volumes:
  mysql_data:

networks:
  mynetwork:
    driver: bridge